#!/bin/bash

# First compile parser for linux
# Get to Parser directory:
cd parser

# We want to remove all linux binaries and helper files
make clean

#Update timestamps for flex because flex cares for some reason.
touch sexp/lex.yy.*

# Build piracy for linux:
make

# Congrats, a linux parser has now been built for you.

# Back to the root directory:
cd ..

# Build Makefiles for linux:
qmake

# clean up for a full build
make clean

# Leave off release if you want a debug build
make 

# Congrats, you're done
