#!/bin/bash

# Run the codegen and get the files
# Build Makefiles for linux:
qmake

# clean up for a full build
make clean

# Leave off release if you want a debug build
make 

# Congrats, you're done
