#!/bin/bash

# Run the codegen and get the files
# Build Makefiles for linux:
qmake

# clean up for a full build
make clean

# Leave off release if you want a debug build
make 
if [ "$?" -ne "0" ]; then
  exit 1
fi

# Congrats, you're done
