texture portRed			./piracy/textures/CastleRed.png
texture portGreen		./piracy/textures/CastleGreen.png
texture portNPC			./piracy/textures/CastleBlack.png
texture pirateGreen		./piracy/textures/pirategreen.png
texture pirateRed		./piracy/textures/piratered.png
texture pirateNPC		./piracy/textures/pirateblack.png
texture treasure		./piracy/textures/coin-Lv-5.png
texture forest			./piracy/textures/Forest.png
texture hills			./piracy/textures/Hills.png
texture grass			./piracy/textures/Grass.png
texture mountains		./piracy/textures/Mountains.png
texture water			./piracy/textures/water.png
