#!/bin/bash

# Build Makefiles for windows:
qmake -spec win32-x-g++
if [ "$?" -ne "0" ]; then
  echo "Could not build the windows makefiles.  Check output."
  exit 1
fi

# Leave off release if you want a debug build
make release
if [ "$?" -ne "0" ]; then
  echo "Could not build the windows binaries.  Check output."
  exit 1
fi

# Clean up windows mess
make clean

# Your visualizer.exe executable will now be in ./release or ./debug
 
# Now reset everything so that it compiles appropriately in linux

# Build linux make files
qmake

# Get to parser directory:
cd ./lib/parser

# Remove windows specific stuff
make clean

# Congrats, you're done
cd ../..

