texture portRed			textures/CastleRedAlt1.png
texture portGreen		textures/CastleGreen.png
texture portNPC			textures/CastleBlack.png
texture pirateGreen	textures/pirategreen.png
texture pirateRed		textures/piratered.png
texture pirateNPC		textures/pirateblack.png
texture shipRed			textures/shipRed1.png
texture shipGreen		textures/shipGreen1.png
texture shipNPC			textures/shipBlack1.png
texture shipDead    textures/ghostShip.png
texture treasure		textures/coin-Lv-5.png
texture forest			textures/Forest.png
texture hills			  textures/Hills.png
texture grass			  textures/Grass.png
texture mountains		textures/Mountains.png
texture fontTexture textures/font1.png
texture proc1       textures/deepWater.png
texture proc2       textures/midWater.png
#texture proc3       textures/midWater.png
texture proc4       textures/shallowWater.png
texture proc5       textures/beach.png
texture proc6       textures/Grass.png
#texture proc7       textures/Grass.png
#texture proc8       textures/Grass.png
texture proc9       textures/tundra.png
#texture proc10      textures/tundra.png
